#!/bin/bash
if [[ $@ == *atmega2560* && $@ == */dev/ttyAMA0* ]]
then
  echo "RPI-ATMega2560";
  sudo strace -o "|/usr/local/share/avrdude-rpi/autoreset2560" -eioctl /usr/local/share/avrdude-rpi/avrdude-original $@
elif [[ $@ == *atmega328* && $@ == */dev/ttyAMA0* ]]
then
  echo "RPI-ATMega328";
  sudo strace -o "|/usr/local/share/avrdude-rpi/autoreset328" -eioctl /usr/local/share/avrdude-rpi/avrdude-original $@
else
  sudo /usr/local/share/avrdude-rpi/avrdude-original $@
fi
